---
- name: Install Java OpenJDK
  package:
    name: java-latest-openjdk-devel
- name: Setup javac alternatives
  alternatives:
    name: javac
    path: auto
- name: Setup java alternatives
  alternatives:
    name: java
    path: auto
- name: Install maven
  package:
    name: maven
  when: ansible_distribution != 'Amazon'
